<?xml version="1.0"?>
<package format="3">
  <name>ch11_cpp_examples</name>
  <version>0.1.0</version>
  <description>Chapter 11 C++ package example.</description>
  <maintainer email="examples@example.com">ROS 2 Book</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
